apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-content
  labels:
    type: local
spec:
  storageClassName: wordpress-content
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/plusone/Desktop/wp-pv"