apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: sl-wordpress
spec:
  ports:
  - port: 80
    nodePort: 30300
    protocol: TCP
    targetPort: wordpress-port
  selector:
    app: wordpress-deployment
  type: NodePort
