apiVersion: v1
kind: Pod
metadata:
  name: aws-ecr-app
  labels:
    app: webserver
spec:
  containers:
  - name: aws-ecr-app
    image: <AWS_ECR_LINK>/<REPOSITORY_NAME>:<TAG>
  imagePullSecrets:
  - name: <NAME_OF_SECRET>
